version: '3.4'

services:
  mongodb:
    container_name: mongo_db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - 27017:27017
    volumes:
      - /var/docker_volumes/mongodb:/data/db
