ersion: '3'

volumes:
  ikev2-vpn-data:

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    env_file:
      - /var/docker_volumes/ipsec/vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    restart: always
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro