version: '3.8'

services:

  agent:
    image: portainer/agent:latest
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent_network
    labels:
      - traefik.enable=false
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ce:2.16.2-alpine
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    # command: ["-H", "tcp://tasks.agent:9001", "--tlsskipverify", "--no-auth"]
    volumes:
      - portainer_data:/data
    networks:
      - portainer_agent_network
      - traefik_net
    ports:
      - 9111:9000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.portainer == true]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_net
        - traefik.http.routers.portainer.entrypoints=websecure
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.rule=Host(`portainer.example.com`)
        - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  portainer_agent_network:
    external: true
    name: "portainer_agent_network"

  traefik_net:
    external: true
    name: "traefik_net"

volumes:
  portainer_data:
