version: '3.8'

networks:
  web-net:
    driver: overlay

services:

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.labels.name == ci-runner
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker_volumes/gitlab-runner/config:/etc/gitlab-runner
    networks:
      - web-net

  register-gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    volumes:
      - /var/docker_volumes/gitlab-runner/config:/etc/gitlab-runner
    deploy:
      restart_policy:
        condition: none
      mode: replicated
      replicas: 4
      placement:
        constraints:
          - node.labels.name == ci-runner
    command:
      - register
      - --non-interactive
      - --locked=false
      - --run-untagged
      - --name=GitLab Runner
      - --tag-list=publish
      - --executor=docker
      - --docker-image=docker:stable
      - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
      - --docker-network-mode=web-net
    environment:
      # - "CONCURRENT=8"
      - "CI_SERVER_URL=<your domain>"
      - "REGISTRATION_TOKEN=<your registeration code>"
    networks:
      - web-net