
version: '3.8'

networks:
  web-net:
    external: true
    name: 'web-net'

services:
  image: sameersbn/gitlab-ci-multi-runner
  volumes:
    - /var/docker_volumes/gitlab-runner:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=
    - RUNNER_TOKEN=
    - RUNNER_DESCRIPTION=
    - RUNNER_EXECUTOR=shell
    - PRIVILEGED=true
  restart: always
