version: '3.4'
services:
  gitlab-runners:
    image: sameersbn/gitlab-ci-multi-runner
    volumes:
    - gitlab-runner-data:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

volumes:
  gitlab-runner-data:
    external: true
