
version: '3.8'

services:
  seq:
      image: datalust/seq:latest
      environment:
        - ACCEPT_EULA=Y
      volumes:
        - /var/docker_volumes/seq-data:/data
      deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints: [node.labels.seq == true]
          labels:
            - traefik.enable=true
            - traefik.docker.network=traefik_net
            - traefik.http.routers.seq.entrypoints=websecure
            - traefik.http.routers.seq.tls=true
            - traefik.http.routers.seq.rule=Host(`seq.example.com`)
            - traefik.http.services.seq.loadbalancer.server.port=80
      networks:
        - traefik_net
          
networks:
  traefik_net:
    external: true
    name: "traefik_net"
  seq-net:
    external: true
    name: "seq-net"
