version: "3.8"
services:
  vault:
    image: vault:latest
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "s_dfoinwEF@w3owenfwionefw#"
    cap_add:
      - IPC_LOCK
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.vault == true]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_net
        - traefik.http.routers.vault.entrypoints=websecure
        - traefik.http.routers.vault.tls=true
        - traefik.http.routers.vault.rule=Host(`vault.example.com`)
        - traefik.http.services.vault.loadbalancer.server.port=8200
    networks:
      - traefik_network
    volumes:
      - /var/docker_volumes/vault/data:/vault/data
      - /var/docker_volumes/vault/logs:/vault/logs

networks:
  traefik_network:
    external: true
    name: "traefik_net"